### ISSUE TITLE
go run build

### ISSUE THREAD

**Issue by 18lkdev** [chenxiao1990/GenMysqlProject#2]
go: GenMysqlProject imports
        github.com/chenxiao1990/GenMysqlProject/ProjectTemplate: github.com/chenxiao1990/GenMysqlProject@v1.0.0: parsing go.mod:
        module declares its path as: gitee.com/290746987/GenMysqlProject
                but was required as: github.com/chenxiao1990/GenMysqlProject
2020/02/10 20:09:33 gowatch.go:135: [ERROR] ============== Build failed ===================

**Comment by chenxiao1990** [comment]
看提示，你可能是通过项目引用的这个工程的1.0版本。因为1.0版本时还在gitee。所以名称有些问题。
你可以直接下载zip 最新代码 进行编译即可。

**Comment by chenxiao1990** [comment]
提交了新的release
